# 容器配置
server:
  port: 8080
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
# 测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
# 生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod
spring:
  profiles:
    active: dev
  datasource:
    druid:
      one: # 数据库连接1
        url: jdbc:mysql://127.0.0.1/springbootdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
        username: root
        password: 0.0001
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 20
        max-wait: 20000
      tow: #数 据库连接2
        url: jdbc:mysql://127.0.0.1/springbootdb2?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
        username: root
        password: 0.0001
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 20
        max-wait: 20000
      max-active: 10 # 初始化大小，最小，最大链接数
      min-idle: 3
      initial-size: 3
      max-wait: 60000 # 连接超时时间
# 取消thymeleaf缓存
  thymeleaf:
    cache: false
# Redis 配置
  redis:
    host: localhost
    password:



## druid配置
## 初始化大小，最小，最大链接数
#spring.datasource.druid.initial-size=3
#spring.datasource.druid.min-idle=3
#spring.datasource.druid.max-active=10
## 连接超时时间
#spring.datasource.druid.max-wait=60000
## 后台登录用户名密码
#spring.datasource.druid.stat-view-servlet.login-username=admin
#spring.datasource.druid.stat-view-servlet.login-password=admin
## 配置StatFilter
#spring.datasource.druid.filter.stat.log-slow-sql=true
#spring.datasource.druid.filter.stat.slow-sql-millis=2000
## Druid 数据源 1 配置，继承spring.datasource.druid.* 配置，相同则覆盖
#spring.datasource.druid.one.max-active=20
#spring.datasource.druid.one.max-wait=10000
## Druid 数据源 2 配置，继承spring.datasource.druid.* 配置，相同则覆盖
#spring.datasource.druid.two.max-active=30
#spring.datasource.druid.two.max-wait=20000

#mybatis 配置

#
### Redis 配置
### Redis数据库索引（默认为0）
#spring.redis.database=0
### Redis服务器地址
#spring.redis.host=127.0.0.1
### Redis服务器连接端口
#spring.redis.port=6379
### Redis服务器连接密码（默认为空）
#spring.redis.password=
### 连接池最大连接数（使用负值表示没有限制）
#spring.redis.pool.max-active=8
### 连接池最大阻塞等待时间（使用负值表示没有限制）
#spring.redis.pool.max-wait=-1
### 连接池中的最大空闲连接
#spring.redis.pool.max-idle=8
### 连接池中的最小空闲连接
#spring.redis.pool.min-idle=0
### 连接超时时间（毫秒）
#spring.redis.timeout=0